services:
  db:
    image: mysql:8.4.0
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=LendingSystem
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    secrets:
      - db-password
    expose:
      - 3306
    networks:
      - private
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=test123
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
    hostname: redis
    networks:
      - private

  backend:
    build:
      context: backend
    environment:
      - DB_PASSWORD=/run/secrets/db-password
    secrets:
      - db-password
    volumes:
      - images:/app/pictures
      - pdfs:/app/pdfs
    expose:
      - 5000
    ports:
      - 5000:5000
    hostname: container
    networks:
      - public
      - private
    depends_on:
      db:
        condition: service_healthy
  
  proxy:
    build: proxy
    restart: always
    volumes:
      - images:/app/pictures
      - pdfs:/app/pdfs
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - public

networks:
  public:
  private:

volumes:
  db-data:
  images:
  pdfs:

secrets:
  db-password:
    file: db/password.txt