services:
  database:
    image: mysql:9.0.1
    ports:
      - 3310:3306
    volumes:
      - database-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MYSQL_DATABASE=LendingSystem
    secrets:
      - db-password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - database

  redis:
    image: redis:8.0-M01
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - database


  backend:
    build: ./backend
    hostname: container
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - pdf-files:/backend/pdfs
      - image-files:/backend/pictures
    env_file:
      - backend.env
    secrets:
      - db-password
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - database
      - public

  frontend:
    build: ./frontend
    depends_on:
      backend:
        condition: service_healthy
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      - pdf-files:/var/www/html/pdfs
      - image-files:/var/www/html/pictures
    networks:
      - public

volumes:
  database-data:
  pdf-files:
  image-files:

networks:
  database:
    internal: true
  public:

secrets:
  db-password:
    file: db-password.txt