"""Replace Picture with more generel File3

Revision ID: 0ce940ce59e2
Revises: 8b8b6afb560b
Create Date: 2024-06-17 17:49:44.211008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0ce940ce59e2'
down_revision: Union[str, None] = '8b8b6afb560b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'file_type',
               existing_type=mysql.ENUM('picture', 'agb', 'other'),
               type_=sa.Enum('picture', 'pdf', 'other', name='filetype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'file_type',
               existing_type=sa.Enum('picture', 'pdf', 'other', name='filetype'),
               type_=mysql.ENUM('picture', 'agb', 'other'),
               existing_nullable=False)
    # ### end Alembic commands ###
