"""Cascade delete for Object and Picture

Revision ID: 194d251bf0f2
Revises: ded8bb72a312
Create Date: 2024-06-02 10:56:50.856992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194d251bf0f2'
down_revision: Union[str, None] = 'ded8bb72a312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
