"""Update identifier to uuid

Revision ID: 1efdcd2e0572
Revises: 7a8e5a393295
Create Date: 2024-06-24 16:26:52.500769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1efdcd2e0572'
down_revision: Union[str, None] = '7a8e5a393295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('session_id', table_name='sessions')
    op.drop_table('sessions')
    op.alter_column('file', 'file_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('group', 'group_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('group_physicalobject', 'group_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('group_physicalobject', 'phys_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('order', 'order_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('organization', 'organization_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('organization_user', 'organization_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('organization_user', 'user_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('physicalobject', 'phys_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('physicalobject_order', 'phys_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('physicalobject_order', 'order_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('physicalobject_organization', 'phys_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('physicalobject_organization', 'organization_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('physicalobject_tag', 'phys_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('physicalobject_tag', 'tag_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('tag', 'tag_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('user', 'user_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('user_order', 'user_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('user_order', 'order_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_order', 'order_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_order', 'user_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('user', 'user_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('tag', 'tag_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('physicalobject_tag', 'tag_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('physicalobject_tag', 'phys_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('physicalobject_organization', 'organization_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('physicalobject_organization', 'phys_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('physicalobject_order', 'order_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('physicalobject_order', 'phys_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('physicalobject', 'phys_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('organization_user', 'user_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('organization_user', 'organization_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('organization', 'organization_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('order', 'order_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('group_physicalobject', 'phys_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('group_physicalobject', 'group_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('group', 'group_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('file', 'file_id',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.create_table('sessions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('expiry', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('session_id', 'sessions', ['session_id'], unique=True)
    # ### end Alembic commands ###
