"""Test2

Revision ID: 24fdf5f5e6da
Revises: 408125d6d04e
Create Date: 2024-05-23 17:52:00.325314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24fdf5f5e6da'
down_revision: Union[str, None] = '408125d6d04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('name', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'name')
    # ### end Alembic commands ###
