"""Test4

Revision ID: 51c772d10b15
Revises: 62be74675d5c
Create Date: 2024-05-23 17:54:12.564371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '51c772d10b15'
down_revision: Union[str, None] = '62be74675d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('name', table_name='test')
    # op.drop_column('test', 'name')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('test', sa.Column('name', mysql.VARCHAR(length=60), nullable=True))
    # op.create_index('name', 'test', ['name'], unique=False)
    pass
    # ### end Alembic commands ###
