"""Test3

Revision ID: 62be74675d5c
Revises: 24fdf5f5e6da
Create Date: 2024-05-23 17:53:16.065793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62be74675d5c'
down_revision: Union[str, None] = '24fdf5f5e6da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'test', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='unique')
    # ### end Alembic commands ###
