"""Donst use Address as seperate class

Revision ID: 6d4f068e9d8a
Revises: ce3bfd3a6216
Create Date: 2024-08-30 12:31:55.761911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d4f068e9d8a'
down_revision: Union[str, None] = 'ce3bfd3a6216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('country', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('postcode', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('street', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('house_number', sa.String(length=10), nullable=True))
    op.drop_column('user', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=120), nullable=True))
    op.drop_column('user', 'house_number')
    op.drop_column('user', 'street')
    op.drop_column('user', 'city')
    op.drop_column('user', 'postcode')
    op.drop_column('user', 'country')
    # ### end Alembic commands ###
