"""Add new propereties to physicalObject

Revision ID: 8b34bdb647f2
Revises: 5320eb3c9825
Create Date: 2024-07-08 09:28:32.860785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8b34bdb647f2'
down_revision: Union[str, None] = '5320eb3c9825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    op.drop_index('session_id', table_name='sessions')
    op.drop_table('sessions')
    op.alter_column('organization_user', 'rights',
               existing_type=mysql.ENUM('organization_admin', 'inventory_admin', 'watcher', 'member'),
               type_=sa.Enum('organization_admin', 'inventory_admin', 'member', 'watcher', name='userrights'),
               existing_nullable=False)
    op.add_column('physicalobject', sa.Column('borrowable', sa.Boolean(), nullable=False))
    op.add_column('physicalobject', sa.Column('lending_comment', sa.String(length=600), nullable=True))
    op.add_column('physicalobject', sa.Column('return_comment', sa.String(length=600), nullable=True))
    op.drop_column('physicalobject', 'storage_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physicalobject', sa.Column('storage_location', mysql.VARCHAR(length=600), nullable=False))
    op.drop_column('physicalobject', 'return_comment')
    op.drop_column('physicalobject', 'lending_comment')
    op.drop_column('physicalobject', 'borrowable')
    op.alter_column('organization_user', 'rights',
               existing_type=sa.Enum('organization_admin', 'inventory_admin', 'member', 'watcher', name='userrights'),
               type_=mysql.ENUM('organization_admin', 'inventory_admin', 'watcher', 'member'),
               existing_nullable=False)
    op.create_table('sessions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('expiry', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('session_id', 'sessions', ['session_id'], unique=True)
    op.create_table('session',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('expiry', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
