"""Replace Picture with more generel File2

Revision ID: 8b8b6afb560b
Revises: c62d1016f4af
Create Date: 2024-06-17 17:20:29.123323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8b6afb560b'
down_revision: Union[str, None] = 'c62d1016f4af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'file', 'group', ['group_id'], ['group_id'])
    op.add_column('organization_user', sa.Column('agb_dont_show', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_user', 'agb_dont_show')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'group_id')
    # ### end Alembic commands ###
