"""Rename delivery_time to return_date

Revision ID: 9733d217dc13
Revises: 0740b884fc26
Create Date: 2024-06-17 11:21:42.480844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9733d217dc13'
down_revision: Union[str, None] = '0740b884fc26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physicalobject_order', sa.Column('return_date', sa.DateTime(), nullable=True))
    op.drop_column('physicalobject_order', 'delivery_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physicalobject_order', sa.Column('delivery_time', mysql.DATETIME(), nullable=True))
    op.drop_column('physicalobject_order', 'return_date')
    # ### end Alembic commands ###
