"""PhysicalObjects individual status and delivery time in order

Revision ID: 9d8a9f9bf162
Revises: 3f84414166ec
Create Date: 2024-06-07 18:12:07.979355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9d8a9f9bf162'
down_revision: Union[str, None] = '3f84414166ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('from_date', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('till_date', sa.DateTime(), nullable=True))
    op.add_column('physicalobject_order', sa.Column('order_status', sa.Enum('pending', 'accepted', 'picked', 'rejected', 'returned', name='orderstatus'), nullable=False))
    op.add_column('physicalobject_order', sa.Column('delivery_time', sa.DateTime(), nullable=True))
    op.drop_column('physicalobject_order', 'till_date')
    op.drop_column('physicalobject_order', 'status')
    op.drop_column('physicalobject_order', 'from_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physicalobject_order', sa.Column('from_date', mysql.DATETIME(), nullable=True))
    op.add_column('physicalobject_order', sa.Column('status', mysql.ENUM('pending', 'accepted', 'picked', 'rejected', 'returned'), nullable=False))
    op.add_column('physicalobject_order', sa.Column('till_date', mysql.DATETIME(), nullable=True))
    op.drop_column('physicalobject_order', 'delivery_time')
    op.drop_column('physicalobject_order', 'order_status')
    op.drop_column('order', 'till_date')
    op.drop_column('order', 'from_date')
    # ### end Alembic commands ###
