"""Fix Object-Picture relation

Revision ID: a01bdde248a3
Revises: e18dbf59de77
Create Date: 2024-05-23 21:02:39.181595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01bdde248a3'
down_revision: Union[str, None] = 'e18dbf59de77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'picture', 'physicalobject', ['physicalobject_id'], ['phys_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'picture', type_='foreignkey')
    # ### end Alembic commands ###
