"""Replace Picture with more generel File

Revision ID: c62d1016f4af
Revises: 9733d217dc13
Create Date: 2024-06-17 16:49:03.167719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c62d1016f4af'
down_revision: Union[str, None] = '9733d217dc13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('physicalobject_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=600), nullable=False),
    sa.Column('file_type', sa.Enum('picture', 'agb', 'other', name='filetype'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization_id'], ),
    sa.ForeignKeyConstraint(['physicalobject_id'], ['physicalobject.phys_id'], ),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('path')
    )
    op.drop_column('picture', 'path')
    op.drop_table('picture')
    op.drop_index('agb', table_name='organization')
    op.drop_column('organization', 'agb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('agb', mysql.VARCHAR(length=600), nullable=True))
    op.create_index('agb', 'organization', ['agb'], unique=True)
    op.create_table('picture',
    sa.Column('picture_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('path', mysql.VARCHAR(length=600), nullable=False),
    sa.Column('physicalobject_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['physicalobject_id'], ['physicalobject.phys_id'], name='picture_ibfk_1'),
    sa.PrimaryKeyConstraint('picture_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.add_column('path', 'picture', ['path'], unique=True)
    op.drop_table('file')
    # ### end Alembic commands ###
