"""Changed length of password hash

Revision ID: ded8bb72a312
Revises: a01bdde248a3
Create Date: 2024-05-29 18:01:25.239898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ded8bb72a312'
down_revision: Union[str, None] = 'a01bdde248a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=False)
    op.create_table('Secret',
    sa.Column('app.secret_key', mysql.VARCHAR(length=100), nullable=False),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
